config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  post"/blogs/confirm",to:"blogs#confirm"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  
  
  validates :title, :content, presence: true
  validates :content, length: {in:1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]


  def index
    @blogs = Blog.all
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)
    
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path, notice: "投稿しました"      
      else
        @error = "投稿失敗しました"
        render "confirm"
      end      
    end    
  end

  def confirm
    @blog = Blog.new(blog_params)
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    acheive = @blog.update(blog_params)
    if acheive === true 
      redirect_to blogs_path, notice: "更新成功"
    else
      redirect_to blogs_path, notice: "更新失敗"
    end
  end

  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_blog
      @blog = Blog.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true) do |form| %>


  <% if @blog.errors.any? %>
    <div id = "error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this @blog from being saved:</h2>
      <ul>
        <% @blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/confirm.html.erb
<% if @blog.errors.any?%>
  <% if !@blog.errors.messages[:title].empty? %>
  <%byebug%>
  <h3>タイトルエラー！！<br><%= @blog.errors.messages[:title]%></h3><br>
  <% end %>
  <% if !@blog.errors.messages[:content].empty? %>
  <h3>コンテントエラー！！<br><%= @blog.errors.messages[:content]%></h3><br>
  <% end%>
<% end%>

<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog,  local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <% if !@blog.errors.any?%>
    <%= form.submit  "登録する" %>
  <% end%>
  <%= form.submit "戻る", name: 'back' %>
<% end %>


app/views/blogs/createa.html.erb
create

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= form_with(model: @blog, local: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <br>
  <br>
  <%= form.label :content %>
  <%= form.text_field :content %>
  <br>
  <br>
  <%= form.submit%>
<% end %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p><%= notice %></p>


<h1>ブログ</h1>
<%= link_to '新しいブログを投稿する', new_blog_path %>
<br>
<br>


<table>
  <thead>
    <tr>
      <td>ブログID</td>
      <td>ブログタイトル</td>
      <td>ブログ内容</td>
      <td>ブログ更新日</td>
    </tr>
  </thead>


  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog[:id] %></td>
        <td><%= blog[:title] %></td>
        <td><%= blog[:content] %></td>
        <td><%= blog[:updated_at] %></td>
        <td><%= link_to '詳細', blog_path(blog.id) %></td>
        <td><%= link_to '編集', edit_blog_path(blog.id) %></td>
        <td><%= link_to '削除', blog_path(blog.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= form_with(model:@blog, local: true, url: "/blogs/confirm" ) do |form|%>

  <%= form.label :title %>
  <%= form.text_field :title %>
  
  <%= form.label :content %>
  <%= form.text_field :content %>
  <br>

  <%= form.submit%>
<% end %>


<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>


<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>